# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0389e5e45caefcbd3768f2f450695419409fd67f8006eba29c6231070b7171e878b1d0596632d6a905f928b9d51092c0ad1bb6cc1af7a3deacd580e67af3927d

test:
  secret_key_base: 0a05332a6107177c5568789e9b99588a23247d8216b77efa9cbf6ee470b65a417db6548122297efd6be88d5d36ec19480a3a99106f766665a993bc1c689e82e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
